---
title: "Example RMD Parameterized"
output: 
  pdf_document:
    includes: 
      in_header: Extra/preamble.tex
      before_body: Extra/doc-prefix.tex
params:
  region: "Northeast"
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

# https://bookdown.org/yihui/rmarkdown/params-knit.html
#https://bookdown.org/yihui/rmarkdown/pdf-document.html#includes
# \newcolumntype{L}[1]{>{\raggedleft\arraybackslash}p{#1\linewidth}}
# https://tex.stackexchange.com/questions/7347/fixed-column-width-table-with-text-left-aligned-in-cells
```

## Some words about following tables

Here's some words. 

```{r readin}

library(tidyverse)
library(glue)
library(knitr)
library(datasets)
options(xtable.comment = FALSE)

statedat <- tibble(
  abb=state.abb,
  area=state.area,
  division=state.division,
  name=state.name,
  region=state.region
)


regdat <- statedat %>%
  filter(region==params$region) %>%
  select(-region)



```



```{r maketable1, results='asis'}




library(xtable)
add.to.row <- list(pos = list(0), command = NULL)
command <- paste0("\\hline\n\\endhead\n",
"\\hline\n",
"\\multicolumn{", dim(regdat)[2] , "}{l}",
"{\\footnotesize Continued on next page}\n",
"\\endfoot\n",
"\\endlastfoot\n")

add.to.row$command <- command

tabout <- xtable(regdat, caption=str_c("States in the ", str_to_lower(params$region), " Census region"))
align(tabout) <- str_c("|l|", str_c(rep("P{.5in}", ncol(regdat)), collapse="|"), "|")
print(tabout, sanitize.text.function= function(x){x}, include.colnames=TRUE, include.rownames = FALSE,
      tabular.environment = "longtable", floating=FALSE,
      add.to.row = add.to.row, caption.placement = "top")


```
